### ISSUE TITLE
Auth error on alive? method of cluster when the token is expired

### ISSUE THREAD

**Issue by theo-remon** [RaoH37/zm-ruby-client#1]
When calling the `alive?` method of an instance of `Zm::Client::Cluster` whose token is expired, a `Zm::Client::AuthError` is raised instead of `false` being returned.

**Comment by theo-remon** [comment]
A `Zm::Client::AuthError` is also raised when calling the `login` method of a cluster with an expired token because the expired token is transmitted in the `AuthRequest`.

This bug occurs in version 2.0.3.

**Comment by RaoH37** [comment]
In curl_request method, default raise object is `Zm::Client::SoapError`
cluster alive? method doesn't use `Zm::Client::AuthError` raise object.

I don't reproduce this issue.

**Comment by RaoH37** [comment]
fixed in version 2.0.4
